config/routes.rb
Notifier::Application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  root 'sites#index'

  resources :sites, except: [:new, :edit]
  resources :categories

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true
  has_many :sites
end

app/models/site.rb
class Site < ActiveRecord::Base
  validates :user_id, :presence => true
  belongs_to :user
  belongs_to :category

  def self.check
    puts 'Doing hard work'
    Site.all.each do |site|
      begin
        oldcontent     =site.content
        oldhash_content=site.hash_content
        site.calc_hash
        if site.hash_content != oldhash_content
          puts 'Change detected ', site.url, ' old hash ', oldhash_content, ' new hash ', site.hash_content
          File.write('tmp/old', oldcontent)
          File.write('tmp/new', site.content)
          system 'diff tmp/old tmp/new >tmp/diff'
          @diff=File.read('tmp/diff')
          UserMailer.change_email(site, @diff).deliver
          site.diff        = @diff
          site.was_changed = true
          site.save!
        end
      rescue Exception => e
        puts "Error checking site "+site.url+" "+e.message
      end
    end
    puts 'End hard work'
  end

  def calc_hash
    clnt = HTTPClient.new
    doc               = Nokogiri::HTML(clnt.get_content(url))
    doc.css('script, link').each { |node| node.remove }
    self.content      = doc.css('body').text #diff with numbers, hash - without
    self.hash_content = Digest::MD5.hexdigest(self.content.gsub(/[0-9]/, ""))
    save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sites, dependent: :destroy

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1/edit
  def edit
  end

  # GET /categories/new
  def new
    @category = Category.new
    render :edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :edit
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      @category.color='#'+@category.color if @category.color[0]!='#'
      @category.save!
      redirect_to categories_path
    else
      render :edit
    end
  end

  #pickup list of categories
  def show
    @categories = Category.all
    @site = Site.find(params[:id])
    render :show, layout: false
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :color, :picture)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :destroy, :update]

  # GET /sites #ALL
  def index
    @sites = Site.where(user_id: current_user ? current_user : User.find(2))
    @categories = Category.select { |cat| cat.sites.where(user_id: current_user ? current_user : User.find(2)).size > 0 }
    @site = Site.new
  end

  # POST /sites
  def create
    @site = current_user.sites.build
    url = params[:site][:url]
    url = "http://#{url}" unless url[0..3]=="http"
    @site.url = url
    begin
      @site.calc_hash
    rescue
      flash[:error] = "Wrong URL!"
    end
    redirect_to root_path
  end

  # DELETE /sites/1
  def destroy
    @site.destroy if current_user
    redirect_to root_path
  end

  def update
    @site.update_attributes(site_params)  if current_user
    redirect_to root_path
  end

  def show
    @site.update_attributes(site_params) if current_user
    render :show, layout: false
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_site
    @site = Site.find(params[:id])
  end

  def site_params
    params.permit(:category_id, :was_changed)
  end
end

app/views/categories/_category.erb
<table>
  <tr>
    <div style="background-color: <%= category.color %>">
      <h2> <%= category.name %> </h2>
    </div>
  </tr>
  <tr>
    <td>
      <%= image_tag(category.picture, width: 100) %>
    </td>
    <td>
      <ul class="sites">
        <%= render @sites.where(category_id: category.id) %>
      </ul>
    </td>
  </tr>
</table>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<script type="text/javascript">
    $(document).ready(
            function () {
                $('#Binded').jPicker();
            });
</script>

<%= form_for(@category) do |f| %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :color %><br>
      <%= f.text_field :color, id: "Binded" %>
    </div>
    <div class="field">
      <%= f.label :picture %><br>
      <%= f.text_field :picture %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', categories_path %> |
<%= link_to 'Home', root_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Color &nbsp&nbsp&nbsp&nbsp</th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
      <tr style="background-color: <%= category.color %>">
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New', new_category_path %>
<%= link_to 'Home', root_path %>

app/views/categories/show.erb
<h1 style="color:white">Select category</h1>

<table>
  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td><%= link_to image_tag(category.picture, width: 80),
                        site_path(@site, category_id: category.id), method: :put %></td>
        <td><%= link_to category.name, site_path(@site, category_id: category.id),
                        class: "pickup", method: :put %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Wellfleet">
  <title>iWatcher <%= current_user.name if current_user %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-33888137-1', 'auto');
      ga('require', 'displayfeatures');
      ga('send', 'pageview');
  </script>

  <style>
      html {
          background: url(assets/bg.jpg) no-repeat center center fixed;
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
      }
  </style>
</head>
<body>

<%= image_tag("topbar.jpg") %>


<div>
  <aside class="span8">
    <section>
      <div>
        <br><br>
        <% if current_user %>
            <img src="<%= current_user.image %>" height="42" width="42">
            Welcome, <%= current_user.name %>!
            <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <% else %>
            Please sign in to your social network <br>
            <%= link_to image_tag("signin.png", width: 150), "/auth/google_oauth2", id: "sign_in" %>
            <%= link_to image_tag("facebook.png", width: 150), "/auth/facebook", id: "sign_in" %>
            <!--<%= link_to image_tag("twitter-logo.png", width: 150), "/auth/twitter", id: "sign_in" %>-->
            <%= link_to link_to image_tag("vkontakte.png", width: 150), "/auth/vkontakte", id: "sign_in" %>
            <br><br><b>iWatcher</b> observes your sites and sends email to you if change is detected. &nbsp See example
            layout below.
            <br>
        <% end %>
      </div>
      <div>
        <%= yield %>
      </div>
      <%= link_to "Forum", "http://extender.tk", target: "_blank" %>
    </section>
  </aside>
  <div class="span3">
    <br> <br><br> <br>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- my -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:300px;height:600px"
         data-ad-client="ca-pub-1351673544337847"
         data-ad-slot="2591225138"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div>
</div>


</body>
</html>

app/views/sites/_site.html.erb
<li>
  <%= link_to site.url, site.url, target: "_blank" %>
  | <%= link_to "Category", category_path(site), data: {:colorbox => true,
                                                        :colorbox_height => '700px',
                                                        :colorbox_width => '400px'} %>
  | <%= link_to "Delete", site, method: :delete, data: {confirm: "You sure?"} %>
  <%= if site.was_changed
        link_to image_tag("new.png", size: "48"),
                site_path(site, was_changed: false), data: {:colorbox => true,
                                                            :colorbox_height => '500px',
                                                            :colorbox_width => '700px'}
      end %>
</li>

app/views/sites/index.erb
<br>
<h1>Your watched resource list</h1>

<%= render @categories %>
<hr>
<ul class="sites">
  <%= render @sites.where(category_id: nil) %>
</ul>

<br>
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<br>
<div class="row">
  <div>
    <%= if current_user
          form_for @site, html: {class: "form-inline"} do |f| %>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Enter URL:
            <%= f.text_field :url, type: "search", class: "span4 offset2" %>
            <%= image_submit_tag("watch.png") %>
        <% end
           end %>
  </div>
</div>

<%= link_to 'Categories', categories_path if current_user && current_user.id==1 %>

app/views/sites/show.erb
<style type="text/css">
    h3 {
        color: #f00;
        font-family: 'Helvetica';
        font-size: 12px;
    }

    h4 {
        color: #00f;
        font-family: 'Helvetica';
        font-size: 12px;
    }
</style>

<%= @site.diff.html_safe %>